import type { FrameEffect, SankeyData, DemoSummary } from './types';

// First 300 bp of HPV16 E1 region (K02718.1, positions 865-1164)
export const DEMO_SEQUENCE =
  'ATGAAACGAAAACGAAAACGAAAATGTTTCAGGACCCACAGGAGCGACCCAGAAAGTTACCACAGTTATGCACAGAGCTGCAAACAACTATACATGATATAAAAATGAAAGAGCTGGACTTTCAGCAACCTACTTTTTTTGACAGCACTGGAAACTACTTACAAAGTGATGAAATAGATGAAGGAGAAGACATGGCTGAACTATCAGAATCAGAAATGGAAATGATGTCAGCAGTTGAGGAATTAAAGCAAAGAAAAGCCATGTCTAAAGAAATGGAAAGAGCAGTAAAGACAGAAGATCAACAAAGGGAAAGTATG';

export const DEMO_SUMMARY: DemoSummary = {
  total_input_variants: 47,
  total_silent_variants: 47,
  total_orfs: 132,
  total_effects: 47,
  reclassified_effects: 14,
  total_silent: 47,
  reclassified: 14,
  frames_affected: 5,
  best_ic50: 142,
};

export const DEMO_SANKEY: SankeyData = {
  nodes: [
    { name: 'Silent Variants' },
    { name: 'Still Silent' },
    { name: 'Missense' },
    { name: 'Stop Gain' },
    { name: 'Start Loss' },
  ],
  links: [
    { source: 0, target: 1, value: 33 },
    { source: 0, target: 2, value: 10 },
    { source: 0, target: 3, value: 3 },
    { source: 0, target: 4, value: 1 },
  ],
};

export const DEMO_VARIANTS: FrameEffect[] = [
  {
    id: 'HPV16_E1_c.456G>A',
    gene: 'E1',
    position: 456,
    frame: 2,
    old_class: 'Silent',
    new_class: 'Missense',
    ref_codon: 'GGA',
    alt_codon: 'GAA',
    ref_aa: 'Gly',
    alt_aa: 'Arg',
    evidence_tier: 3,
    synmicdb_score: 0.84,
    narrative:
      'This synonymous G to A substitution at HPV16 position 456 is silent in the canonical E1 frame but introduces a Gly to Arg change in overlapping frame 2. The resulting peptide GILGFVFTL is predicted to bind HLA-A*02:01 with IC50 142 nM. SynMICdb records this variant in 12 independent cancer samples, suggesting recurrent positive selection.',
    peptides: [
      { sequence: 'GILGFVFTL', allele: 'HLA-A*02:01', ic50: 142, rank: 1.2 },
      { sequence: 'FVFTLGILG', allele: 'HLA-A*02:01', ic50: 380, rank: 3.1 },
      { sequence: 'TLFGILGFV', allele: 'HLA-B*07:02', ic50: 520, rank: 4.7 },
    ],
  },
  {
    id: 'HPV16_E7_c.712T>C',
    gene: 'E7',
    position: 712,
    frame: 4,
    old_class: 'Silent',
    new_class: 'Stop Gain',
    ref_codon: 'TGG',
    alt_codon: 'TAG',
    ref_aa: 'Trp',
    alt_aa: '*',
    evidence_tier: 2,
    synmicdb_score: null,
    narrative:
      'This T to C transition at HPV16 position 712 is synonymous in E7 but introduces a premature stop codon in frame 4, truncating a putative overlapping ORF at residue 45. OpenProt 2.0 confirms an annotated AltORF overlapping this position.',
    peptides: [
      { sequence: 'YMLDLQPET', allele: 'HLA-A*02:01', ic50: 390, rank: 3.8 },
      { sequence: 'DLQPETTTE', allele: 'HLA-A*02:01', ic50: 890, rank: 8.2 },
    ],
  },
  {
    id: 'HPV16_E2_c.1089C>T',
    gene: 'E2',
    position: 1089,
    frame: 1,
    old_class: 'Silent',
    new_class: 'Missense',
    ref_codon: 'CAC',
    alt_codon: 'CAT',
    ref_aa: 'His',
    alt_aa: 'Tyr',
    evidence_tier: 2,
    synmicdb_score: null,
    narrative:
      'The C to T synonymous change at position 1089 in E2 alters the codon in frame 1 from His to Tyr. OpenProt records an AltORF at this locus. The Tyr substitution introduces a new phosphorylation consensus site that may affect the stability of the alternative protein product.',
    peptides: [
      { sequence: 'KFYGLTHCV', allele: 'HLA-A*02:01', ic50: 220, rank: 2.1 },
      { sequence: 'FYGLTHCVS', allele: 'HLA-B*07:02', ic50: 460, rank: 4.3 },
    ],
  },
  {
    id: 'HPV16_L1_c.5521A>G',
    gene: 'L1',
    position: 5521,
    frame: 3,
    old_class: 'Silent',
    new_class: 'Missense',
    ref_codon: 'ATT',
    alt_codon: 'GTT',
    ref_aa: 'Ile',
    alt_aa: 'Val',
    evidence_tier: 1,
    synmicdb_score: null,
    narrative:
      'This A to G change in the major capsid protein L1 is silent in the canonical frame but results in an Ile to Val substitution in frame 3. The peptide generated from this overlapping ORF fragment shows moderate MHC binding affinity.',
    peptides: [
      { sequence: 'IVTGNTNTV', allele: 'HLA-A*02:01', ic50: 580, rank: 5.6 },
    ],
  },
  {
    id: 'HPV16_E6_c.340G>A',
    gene: 'E6',
    position: 340,
    frame: 5,
    old_class: 'Silent',
    new_class: 'Missense',
    ref_codon: 'GGC',
    alt_codon: 'AGC',
    ref_aa: 'Gly',
    alt_aa: 'Ser',
    evidence_tier: 3,
    synmicdb_score: 0.71,
    narrative:
      'The E6 oncogene silent variant at position 340 generates a Gly to Ser change in reading frame 5, creating a potential O-glycosylation site. SynMICdb records this variant with a recurrence score of 0.71 across cervical cancer datasets.',
    peptides: [
      { sequence: 'QLCTELQTT', allele: 'HLA-A*02:01', ic50: 168, rank: 1.6 },
      { sequence: 'LCTELQTTL', allele: 'HLA-A*02:01', ic50: 295, rank: 2.8 },
      { sequence: 'ELQTTLHEY', allele: 'HLA-B*07:02', ic50: 610, rank: 5.9 },
    ],
  },
  {
    id: 'HPV16_E4_c.3382T>C',
    gene: 'E4',
    position: 3382,
    frame: 6,
    old_class: 'Silent',
    new_class: 'Missense',
    ref_codon: 'TCT',
    alt_codon: 'CCT',
    ref_aa: 'Ser',
    alt_aa: 'Pro',
    evidence_tier: 2,
    synmicdb_score: null,
    narrative:
      'Silent in the E4 spliced transcript, this T to C change in frame 6 results in Ser to Pro substitution in an overlapping ORF. Proline introduces a structural kink that likely disrupts an alpha-helix. OpenProt confirms the AltORF with experimental evidence from ribosome profiling data.',
    peptides: [
      { sequence: 'KPNPSMFWL', allele: 'HLA-A*02:01', ic50: 340, rank: 3.3 },
    ],
  },
  {
    id: 'HPV16_L2_c.4888G>T',
    gene: 'L2',
    position: 4888,
    frame: 2,
    old_class: 'Silent',
    new_class: 'Missense',
    ref_codon: 'GAA',
    alt_codon: 'TAA',
    ref_aa: 'Glu',
    alt_aa: 'Lys',
    evidence_tier: 1,
    synmicdb_score: null,
    narrative:
      'This variant in L2 (minor capsid protein) is synonymous in the canonical reading frame but causes a charge-reversal Glu to Lys substitution in frame 2. The change may alter protein-protein interactions in the overlapping ORF product.',
    peptides: [
      { sequence: 'NKPIFGGST', allele: 'HLA-A*02:01', ic50: 750, rank: 7.3 },
    ],
  },
  {
    id: 'HPV16_E1_c.512A>G',
    gene: 'E1',
    position: 512,
    frame: 3,
    old_class: 'Silent',
    new_class: 'Missense',
    ref_codon: 'AAG',
    alt_codon: 'GAG',
    ref_aa: 'Lys',
    alt_aa: 'Glu',
    evidence_tier: 3,
    synmicdb_score: 0.62,
    narrative:
      'This recurrently observed A to G change in E1 helicase is synonymous in the canonical frame but generates a Lys to Glu substitution in frame 3. SynMICdb records this in 8 cervical and 3 head-and-neck squamous cell carcinoma samples.',
    peptides: [
      { sequence: 'ELLGEEDLA', allele: 'HLA-A*02:01', ic50: 198, rank: 1.9 },
      { sequence: 'LLGEEDLAF', allele: 'HLA-A*02:01', ic50: 410, rank: 4.0 },
    ],
  },
  {
    id: 'HPV16_E2_c.2755C>T',
    gene: 'E2',
    position: 2755,
    frame: 1,
    old_class: 'Silent',
    new_class: 'Stop Gain',
    ref_codon: 'CAG',
    alt_codon: 'TAG',
    ref_aa: 'Gln',
    alt_aa: '*',
    evidence_tier: 2,
    synmicdb_score: null,
    narrative:
      'This C to T transition creates a premature stop codon in frame 1 of a documented AltORF overlapping E2. The truncated product of 78 amino acids lacks the C-terminal domain required for membrane anchoring. OpenProt catalogues the full-length isoform with ribosomal profiling evidence.',
    peptides: [
      { sequence: 'QSTTIASSL', allele: 'HLA-A*02:01', ic50: 470, rank: 4.6 },
    ],
  },
  {
    id: 'HPV16_E5_c.3897G>C',
    gene: 'E5',
    position: 3897,
    frame: 4,
    old_class: 'Silent',
    new_class: 'Missense',
    ref_codon: 'GAG',
    alt_codon: 'CAG',
    ref_aa: 'Glu',
    alt_aa: 'Gln',
    evidence_tier: 1,
    synmicdb_score: null,
    narrative:
      'Silent in the E5 viroporin, this G to C substitution alters Glu to Gln in frame 4. This frame 4 ORF may encode a cryptic peptide relevant to immune evasion during early infection.',
    peptides: [
      { sequence: 'FLLTFCLCL', allele: 'HLA-A*02:01', ic50: 830, rank: 8.1 },
    ],
  },
  {
    id: 'HPV16_E7_c.813C>A',
    gene: 'E7',
    position: 813,
    frame: 5,
    old_class: 'Silent',
    new_class: 'Missense',
    ref_codon: 'CCC',
    alt_codon: 'ACC',
    ref_aa: 'Pro',
    alt_aa: 'Thr',
    evidence_tier: 3,
    synmicdb_score: 0.55,
    narrative:
      'The C to A transversion in E7 at position 813 introduces a Pro to Thr substitution in frame 5. Threonine may serve as a phosphorylation acceptor, creating a novel signaling epitope. SynMICdb recurrence score of 0.55 indicates moderate enrichment in cancer samples.',
    peptides: [
      { sequence: 'TPTTLHEYM', allele: 'HLA-A*02:01', ic50: 185, rank: 1.8 },
      { sequence: 'PTTLHEYML', allele: 'HLA-B*07:02', ic50: 320, rank: 3.1 },
    ],
  },
  {
    id: 'HPV16_L1_c.6100T>A',
    gene: 'L1',
    position: 6100,
    frame: 6,
    old_class: 'Silent',
    new_class: 'Stop Gain',
    ref_codon: 'TCA',
    alt_codon: 'TAA',
    ref_aa: 'Ser',
    alt_aa: '*',
    evidence_tier: 1,
    synmicdb_score: null,
    narrative:
      'This T to A transversion in L1 creates a stop codon in reading frame 6, prematurely terminating an overlapping ORF at position 52. The truncated peptide fragment may be presented via MHC class I through the NMD-linked antigen presentation pathway.',
    peptides: [
      { sequence: 'SSTTDTPST', allele: 'HLA-A*02:01', ic50: 920, rank: 9.0 },
    ],
  },
  {
    id: 'HPV16_E6_c.298T>G',
    gene: 'E6',
    position: 298,
    frame: 2,
    old_class: 'Silent',
    new_class: 'Missense',
    ref_codon: 'TTG',
    alt_codon: 'GTG',
    ref_aa: 'Leu',
    alt_aa: 'Val',
    evidence_tier: 2,
    synmicdb_score: null,
    narrative:
      'This conservative Leu to Val substitution in a frame 2 ORF overlapping E6 generates a neoantigen with measurable HLA-A*02:01 binding affinity. OpenProt confirms the AltORF with 4 supporting peptide spectrum matches from cancer proteomics datasets.',
    peptides: [
      { sequence: 'VLKDCFADY', allele: 'HLA-A*02:01', ic50: 260, rank: 2.5 },
    ],
  },
  {
    id: 'HPV16_E1_c.890C>A',
    gene: 'E1',
    position: 890,
    frame: 1,
    old_class: 'Silent',
    new_class: 'Start Loss',
    ref_codon: 'ATG',
    alt_codon: 'TTG',
    ref_aa: 'Met',
    alt_aa: 'Leu',
    evidence_tier: 1,
    synmicdb_score: null,
    narrative:
      'This C to A change destroys the initiator methionine of a frame 1 AltORF within E1, preventing translation of a 94 amino acid cryptic protein. Loss of this translation initiation site may have subtle effects on viral replication kinetics.',
    peptides: [
      { sequence: 'LLASPAASL', allele: 'HLA-A*02:01', ic50: 1100, rank: 10.5 },
    ],
  },
];
